#!/bin/bash


options="Enable\nDisable"

function vpnUp {
	ls /etc/wireguard | cut -f 1 -d . | rofi -dmenu -p "Enable"
}


function vpnDown {
	ip link show type wireguard | cut -f 2 -d : | sed -e '/link\/none/d' | rofi -dmenu -p "Disable"
}


prompt=$(echo -e "$options" | rofi -dmenu -p "Enable/Disable VPN?")


case $prompt in
	"Enable")
	vpnUpRes=$(vpnUp)
	if [ -n "$vpnUpRes" ];
	then
		pkexec wg-quick up $vpnUpRes
	fi
	;;
	"Disable")
	vpnDownRes=$(vpnDown)
	if [ -n "$vpnDownRes" ];
	then
		pkexec wg-quick down $vpnDownRes
	fi
	;;
esac
